name: 'Jupiter Pipeline'

on:
  push:
    branches:
      - main


permissions:
  contents: read
  id-token: write

jobs:
  deploy:
    name: 'AKSCluster'
    runs-on: ubuntu-latest


    defaults:
      run:
        shell: bash

    steps:

    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    
    - name: Checkout Git Repo
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}

    - name: Build Docker image
      run: |
        docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/jupiter:latest .
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/jupiter:latest


    - name: Set up kubectl
      uses: azure/k8s-set-context@v1
      with:
        kubeconfig: ${{ secrets.KUBE_CONFIG_DATA }}
      
    - name: Apply Kubernetes manifest
      run: |
        kubectl apply -f deployment.yaml
