name: 'Jupiter Pipeline'

on:
  push:
    branches:
      - main


permissions:
  contents: read
  id-token: write

jobs:
  deploy:
    name: 'AKSCluster'
    runs-on: ubuntu-latest


    defaults:
      run:
        shell: bash

    steps:

    - name: 'Azure OIDC login'
      uses: azure/login@v1
      with:
        client-id: ${{ secrets.ARM_CLIENT_ID }}
        tenant-id: ${{ secrets.ARM_TENANT_ID }}
        subscription-id: ${{ secrets.ARM_SUBSCRIPTION_ID }}

    - name: Kubeconfig  
      uses: azure/aks-set-context@v3
      with:
        resource-group: 'demo_rg'
        cluster-name: 'jupiter-aks-cluster'
    
    - name: Checkout Git Repo
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}

    - name: Build Docker image
      run: |
        docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/jupiter:latest .
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/jupiter:latest


    - name: Set up kubectl
      uses: marcofranssen/setup-kubectl@v0.3.0
      id: kubectl
      
    - name: Apply Kubernetes manifest
      run: |
        kubectl apply -f deployment.yaml
